### ISSUE TITLE
cordova building andriod app

### ISSUE THREAD

**Issue by chandrakant-bachhav** [AmitXShukla/Angular-Cordova-Google-PlayStore-Publish#1]
I was already added **_cordova platform add android_** command 
But still showing below error on cordova run andriod

`(node:13932) UnhandledPromiseRejectionWarning: Error: The platform "andriod" does not appear to have been added to this project.
    at Object.getPlatformApi (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:46:15)
    at C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:54:38
    at Array.map (<anonymous>)
    at C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:52:47
    at _fulfilled (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)`

Please help me ASAP.

**Comment by AmitXShukla** [comment]
Please fix typo in your Run command.
cordova run andriod 
should be
cordova run android
